//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public int kayitId { get; set; }
        public int kayitDersiAlanOgrId { get; set; }
        public int kayitDerslerId { get; set; }
    
        public virtual DersiAlanOgr DersiAlanOgr { get; set; }
        public virtual Dersler Dersler { get; set; }
    }
}
