//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB02Entities : DbContext
    {
        public DB02Entities()
            : base("name=DB02Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DersiAlanOgr> DersiAlanOgr { get; set; }
        public virtual DbSet<Dersler> Dersler { get; set; }
        public virtual DbSet<Kayit> Kayit { get; set; }
        public virtual DbSet<Soru> Soru { get; set; }
        public virtual DbSet<Uye> Uye { get; set; }
    }
}
