//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soru
    {
        public int SoruId { get; set; }
        public string soru1 { get; set; }
        public string oA { get; set; }
        public string oB { get; set; }
        public string oC { get; set; }
        public string oD { get; set; }
        public string ans { get; set; }
        public int UyeId { get; set; }
    
        public virtual Uye Uye { get; set; }
    }
}
